[package]
name = "astroport"
version = "2.10.0"
authors = ["Astroport"]
edition = "2021"
description = "Common Astroport types, queriers and other utils"
license = "Apache-2.0"
repository = "https://github.com/astroport-fi/astroport"
homepage = "https://astroport.fi"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
injective = ["injective-math", "thiserror"]

[dependencies]
cw20 = { version = "0.15" }
cosmwasm-std = { version = "1.1" }
uint = "0.9"
cw-storage-plus = "0.15"
itertools = "0.10"
cosmwasm-schema = "1.1"
cw-utils = "1.0"
cw3 = "1.0"

# optional
injective-math = { version = "0.1.14", optional = true }
thiserror = { version="1.0", optional = true }
